const Map<String, String> en = {
  // TEXT
  'all': 'All',
  'ship': 'ship',
  'car': 'car',
  'running': 'Online',
  'run': 'Online',
  'pause': 'Pause',
  'pauseMax': 'Pause',
  'pauseMin': 'Pause',
  'nosign': 'No sign',
  'noGPS': 'No GPS',
  'search': 'Search...',
  'searching': 'Searching',
  'input-id': 'Please input verhical number',
  'create': 'Create',
  'loading': 'Loading...',
  'update-successfully': 'Update successfully',
  'no-alter': 'No data...',
  'no-data-less': 'No data',
  'no-exp-less': 'Expired',
  'no-internet': 'Please check your internet connection..',
  'info': 'Info',
  'location': 'Location',
  'history': 'History',
  'no-device': 'Not device',
  'no-sign-less': 'No Sign',
  'addr': 'Address',
  'day': 'day',
  'month': 'month',
  'year': 'year',
  'hour': 'hour',
  'minutes': 'minutes',
  'seconds': 'seconds',
  'hotline': 'Hotline',
  'phone-call': '0916 82 28 38',
  'total': 'Total',
  'orther': 'Orther',
  'dv-noCam': 'The device does not support the camera...',
  'developing': 'The function is developing...',
  'dateEnd': 'Select a end date',
  'dateStart': 'Select a start date',
  'updating': 'Updating',
  'update': 'Update',
  // AUTHENTICATION
  'username': 'Username',
  'username-desc': 'User name',
  'username-invalid': 'Username invalid or not found',
  'password': 'Password',
  'password-desc': 'Password input',
  'password-err': 'Password invalid or not found',
  'password-invalid': 'Password invalid or not found',
  'password-old': 'Password',
  'password-new': 'Password new',
  'password-confirm': 'Password confirm',
  'page-password': 'Please contact the call center to reset your password.',
  'page-create-account':
      'Please contact the operator to create a device login account.',
  'password-fogot': 'Forgot your password',
  'password-change': 'Change password',
  'signIn': 'Sign In',
  'signOut': 'Sign Out',
  'signUp': 'Sign Up',
  'account-none': "Don't have an account",
  'account-create': 'Create account',
  'phoneNumber': 'Phone number',
  'account': 'Account',
  'email': 'Email',
  'login': 'Login',
  // MENU
  'home-map': 'Home',
  'dv-detail': 'Detail',
  'alter': 'Alter',
  'picture': 'Picture',
  'camera': 'Camera',
  'list': 'List',
  'report': 'Reports',
  'setting': 'Setting',
  // SETTING
  'common': 'Common',
  'language': 'Language',
  'map': 'Map',
  'coordinates': 'Coordinates',
  'velocity': 'Velocity',
  'vietnamese': 'Vietnamese',
  'decimal': 'Decimal coordinates',
  'DM': 'DM coordinates',
  'DMS': 'DMS coordinates',
  'nautical': 'Nautical',
  'mile': 'Mile',

  'security': 'Security',
  'lockAppInBackground': 'Lock app in background',
  'useFingerprint': 'Use fingerprint',
  'allowApplicationToAccessStoredFingerprint':
      'Allow application to access stored fingerprint IDs.',
  'enableNotifications': 'Enable notifications',

  'misc': 'Misc',
  'policy': 'Policy',
  'version': 'Version',
  // REPORT
  'rpHistory': 'History',
  'rpSpeed': 'Speed running',
  'rpDistance': 'Distance',
  'rpOverMap': 'Over map',
  'rpOverSpeed': 'Over speed',
  'rpOverRun': 'Over running',
  'rpPause': 'Pause',
  'rpTimeDriver': 'Driver time',
  'rpTotalByCar': 'Car total',
  'rpTotalByShip': 'Ship total',
  'rpTotalByDriver': 'Driver total',
  // INFO
  'device-info': 'Info',
  'device-edit': 'Edit',
  'device-name': 'Name',
  'device-type': 'Type',
  'status': 'Status',
  'ACC': 'ACC',
  'time-update': 'Date save',
  'speed': 'Speed',
  'latitude': 'Latitude',
  'longitude': 'Longitude',
  'expiration': 'Expuration date',
  'vehical-number': 'License plate',
  // DASHBOARD
  'list-car': 'List',
};
